# dbt_project.yml dosyanızın EN BAŞI
name: 'my_new_project'  # <-- Burası, dbt'nin ilk aradığı isimdir. Girinti OLMAMALI!
config-version: 2
profile: 'dbt_project' # (Sizin için BigQuery'ye bağlanmayı sağlayan profil adı)

# ...

models:
  my_new_project: # <-- Buradaki isim, yukarıdaki name ile AYNI OLMALIDIR!
    mart:
      +materialized: table 
      
      finance:
        +schema: finance